config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations'
  }

  devise_scope :user do
    get 'users/new_address_preset', to: 'users/registrations#new_address_preset'
    post 'users/create_address_preset', to: 'users/registrations#create_address_preset'
  end

  resources :users, only: [:show]

  root to: 'items#index'
  resources :tags, only: [:index]
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
    collection do
      get 'search'
    end

    member do
      get :purchase_confirm
      post :purchase
    end
  end
  # resources :comments, only: [:destroy]
  resources :cards, only: [:index, :new, :create, :destroy]
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :memberships, only: [:new, :create]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates_uniqueness_of :item_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item

  # お気に入り登録
  def create
    @favorite = Favorite.create(user_id: current_user.id, item_id: @item.id)
    count_favorites
  end
  # お気に入り削除
  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, item_id: @item.id)
    @favorite.destroy
    count_favorites
  end

  private
  def set_item
    @item = Item.find(params[:item_id])
  end

  def count_favorites
    @favorites_count = Favorite.where(item_id: @item.id).count
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if !Favorite.exists?(user_id: current_user.id, item_id: item.id) %>
  <%= link_to item_favorites_path(item_id: item.id), method: :post, remote: true, class: "favorite-btn"  do %>
    <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
    <span>お気に入り <%= favorites_count %></span>
  <% end %>
<% else %>
  <%= link_to item_favorites_path(item_id: @item.id), method: :delete, remote: true, style: "background-color: #ffb340",class: "favorite-btn"  do %>
    <span>お気に入り登録済</span>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
document.getElementById('fav').innerHTML = "<%= j(render partial: 'favorites/favorite', locals: { item: @item, favorites_count: @favorites_count }) %>";

app/views/favorites/destroy.js.erb
document.getElementById('fav').innerHTML = "<%= j(render partial: 'favorites/favorite', locals: { item: @item, favorites_count: @favorites_count }) %>";