config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations'
  }

  devise_scope :user do
    get 'users/new_address_preset', to: 'users/registrations#new_address_preset'
    post 'users/create_address_preset', to: 'users/registrations#create_address_preset'
  end

  resources :users, only: [:show]

  root to: 'items#index'
  resources :tags, only: [:index]
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
    collection do
      get 'search'
    end

    member do
      get :purchase_confirm
      post :purchase
    end
  end
  # resources :comments, only: [:destroy]
  resources :cards, only: [:index, :new, :create, :destroy]
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :memberships, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  
  validates :nickname, presence: true, uniqueness: {case_sensitive: true}
  validates :birth_date, presence: true
  validates :password, presence: true, format: {with: /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d_-]{6,}+\z/} 

  with_options presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]+\z/} do
  validates :first_name
  validates :last_name
  end

  with_options presence: true, format: {with: /\A([ァ-ン]|ー)+\z/} do
  validates :first_name_kana
  validates :last_name_kana
  end

  has_many :items
  has_many :orders
  has_many :comments
  has_one :card, dependent: :destroy
  has_one :address_preset
  has_many :sns_credentials
  has_many :favorites, dependent: :destroy
  has_many :items, through: :favorites
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_one :membership

  # 最終的にuserのインスタンスを返すクラスメソッド
  # SNSと同emailのユーザが存在すればそのユーザを返す。いなければuserを作成し返す。
  def self.from_sns_credential(sns, auth)
    # snsの情報が既にDBにあった場合は、2回目以降のログインなので紐づくuserを返す
    return sns.user if sns.persisted?
    # snsの情報がDBにない場合
    # 既存ユーザへSNSサービス連携or新規ユーザ登録
    user = User.where(email: auth.info.email).first_or_initialize
    if user.persisted?
      user.sns_credentials << sns
      user.save
    else
      user.nickname = auth.info.name
    end
    user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # facebook経由のログインの場合は、アカウント選択後、facebookメソッドにレスポンスが来ます。
  def facebook
    authorization
  end

  # google経由のログインの場合は、アカウント選択後、googleメソッドにレスポンスが来ます。
  def google_oauth2
    authorization
  end

  private

  def authorization
    auth = request.env["omniauth.auth"]
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_initialize
    @user = User.from_sns_credential(sns, auth)

    if @user.persisted?
      # @userがDBにいるならば: ログインしてトップページへ飛ばす
      sign_in_and_redirect @user, event: :authentication
    else
      # @userがDBにいないならば: ユーザ新規ログイン画面に遷移させる。
      # sns経由であることをウィザード形式の最後まで保持しておくためにsessionに保存する。
      session["devise.regist_data"] ||= {}
      session["devise.regist_data"]["sns"] = sns.attributes
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :session_has_not_user_data, only: [:new_address_preset, :create_address_preset]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if session["devise.regist_data"] && session["devise.regist_data"]["sns"]
      password = Devise.friendly_token[8,12] + "1a"
      params[:user][:password] = password
      params[:user][:password_confirmation] = password
    end

    @user = User.new(sign_up_params)
    ## @userがバリデーションに引っかかるなら入力させなおす
    unless @user.valid?
      render :new and return
    end
    ## @userがバリデーションをパスするならsessionに入れてお
    ## attributesメソッドは、@userの属性値をハッシュで取得するメソッド

    session["devise.regist_data"] ||= {}
    session["devise.regist_data"][:user] = @user.attributes
    ## passwordは@user.attributesに含まれないのでparamsから別途取得する
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    ## newaddress_presetのビューで使用する@addressを定義（@userに紐づけておく）
    @address_preset = @user.build_address_preset
    ## newaddress_presetのビューを表示させる
    render :new_address_preset
  end

  def create_address_preset
    ## sessionに入っているuserの情報を元に@userを定義しなおす
    @user = User.new(session["devise.regist_data"]["user"])
    @address_preset = AddressPreset.new(address_preset_params)

    @sns = SnsCredential.new(session["devise.regist_data"]["sns"])

    ## @userに@address_presetを紐づける
    @user.build_address_preset(@address_preset.attributes)
    
    @user.sns_credentials.new(@sns.attributes)

    ## @userがバリデーションに引っかかるなら入力させなおす
    unless @user.valid?
      render :new_address_preset and return
    end
    @user.save
    session["devise.regist_data"]["user"].clear
    session["devise.regist_data"]["sns"]&.clear
    ## ログイン状態にする
    sign_in(:user, @user)
  end

  private

  def address_preset_params
    params.require(:address_preset).permit(:postal_code, :prefecture, :city, :addresses, :building, :phone_number)
  end

  def session_has_not_user_data
    redirect_to root_path, alert: "ユーザー情報がありません" unless session["devise.regist_data"]
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def show
    ## お気に入り一覧
    favorites = Favorite.where(user_id: current_user.id).pluck(:item_id)  # ログイン中のユーザーのお気に入りのitem_idカラムを取得
    @favorite_items = Item.find(favorites)     # itemsテーブルから、お気に入り登録済みのレコードを取得

    ## DM機能
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id != current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
    end

    @m = @user.membership

    ## 売買履歴
    @total_pay = total_payment(@user)
    @total_sales = total_sales(@user)

    ## カードが登録されていないならここで終了
    return unless current_user.card.present?
    Payjp.api_key = ENV["PAYJP_SK"] # 環境変数を読み込む
    customer = Payjp::Customer.retrieve(current_user.card.customer_token) # 先程のカード情報を元に、顧客情報を取得
    @card = customer.cards.first
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/header" %>
<div id="user-wrapper">
  <div id ="user-header">
    <h1 id="user-name"><%= @user.nickname %>さんのマイページ</h1> 
    <div id="user-dm">
      <% if @user.id != current_user.id %>
        <% if @isRoom %>
          <%= link_to room_path(@roomId), class: "dm-btn" do %>
            <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
            <span>DMを送る</span>
          <% end %>
        <% else %>
          <%= form_with url: rooms_path, local: true do |f| %>
            <%= f.hidden_field :user_id, value: @user.id %>
            <%= f.button type: 'submit', class: "dm-btn" do %>
              <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
              <span>DMを送ってみる<span>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <% if @m %>
      <div id="user-membership">
      <div class="rank"><small>ネイバーランク</small><br><%= @m.rank.name %></div>
      <%= image_tag @m.rank.image %>
      <%= image_tag @m.image, class:"membership-image" %>
      </div>
    <% end %>
  </div>

  <div id="profile-wrapper">
    <div id="profile">
      <div class="detail-title">
        ユーザー情報
      </div>
      <div class="detail-info">
      <ul>
        <li>氏名：<%= @user.first_name %> <%= @user.last_name%>（<%= @user.first_name_kana %> <%= @user.last_name_kana %>）</li>
        <li>生年月日：<%= @user.birth_date.strftime("%Y年%m月%d日") %></li>
        <li>購入商品数：<%= @user.orders.count %></li>
        <li>売上総額：<%= @total_sales.to_s(:delimited) %> 円</li>
        <li>購入総額：<%= @total_pay.to_s(:delimited) %> 円</li>
      </ul>


      </div>
    </div>
    <% if @user.id == current_user.id %>
    <div id="card-wrapper">
      <div class="detail-title">
        クレジットカード登録情報
      </div>
      <% if current_user.card.present? %>

      <div class="card-detail__page-title">
        <h2>カード情報<h2>
      </div>

      <div class="card-detail__card-info">
        【カード番号】
        <br>
        <%= "**** **** **** " + @card[:last4] %>
        <%# カード番号の下4桁を取得 %>
        <br>
        【有効期限】
        <br>
        <%= @card[:exp_month] %>
        <%# 有効期限の「月」を取得 %>
        /
        <%= @card[:exp_year] %>
        <%# 有効期限の「年」を取得 %>
      </div>

      <%= link_to "クレジットカードを削除する", card_path(current_user.card), method: :delete, id: "destroy-card-link"%>

      <% else %>
      カードがありません。
      <br>
      <%= link_to "クレジットカードを登録する", new_card_path, id: "new-card-link"%>
      <% end %>
    </div>
    <% end %>
  </div>

  <div id="favorite-wrapper">
    <div class='item-contents'>
      <%= link_to 'お気に入り商品', "#", class: "subtitle" %>
      <ul class='item-lists'>
      <% if @favorite_items.length != 0 %>
      <% @favorite_items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.images[0], class: "item-img" %>

            <% if item.order %>
              <div class='sold-out'>
                <span>Sold Out!!</span>
              </div>
            <% end %>

          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= item.name %>
            </h3>
            <div class='item-price'>
              <span><%= item.price %>円<br>(税込み)</span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'><%= item.favorites.count %></span>
              </div>
            </div>
          </div>
          <% end %>
        </li>
        <% end %>
        <% else %>
        <h2>お気に入り商品はありません</h2>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<%= render "shared/footer" %>