config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations'
  }

  devise_scope :user do
    get 'users/new_address_preset', to: 'users/registrations#new_address_preset'
    post 'users/create_address_preset', to: 'users/registrations#create_address_preset'
  end

  resources :users, only: [:show]

  root to: 'items#index'
  resources :tags, only: [:index]
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
    collection do
      get 'search'
    end

    member do
      get :purchase_confirm
      post :purchase
    end
  end
  # resources :comments, only: [:destroy]
  resources :cards, only: [:index, :new, :create, :destroy]
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :memberships, only: [:new, :create]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_one :order
  has_many :comments
  has_many :item_tag_relations, dependent: :destroy
  has_many :tags, through: :item_tag_relations
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :scheduled_delivery
  belongs_to :shipping_fee_status
  belongs_to :prefecture
  belongs_to :sales_status
  belongs_to :category

  with_options presence: true do
    validates :images
    validates :name
    validates :price
    validates :info
  end

  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than: 10000000 , message: 'は300円以上1000万円未満の範囲で入力してください' }
  validates :price, numericality: { with: /\A[0-9]+\z/, message: 'は半角数字で入力してください' }



  def previous
    Item.where("id < ?", self.id).order("id DESC").first
  end

  def next
    Item.where("id > ?", self.id).order("id ASC").first
  end
end

app/models/item_form.rb
class ItemForm
  include ActiveModel::Model
  ## ItemFormクラスのオブジェクトがitemモデルの属性を扱えるようにする
  include ActiveModel::Attributes
  attribute :name,  :string
  attribute :info,  :string
  attribute :category_id, :big_integer
  attribute :sales_status_id, :big_integer
  attribute :shipping_fee_status_id, :big_integer
  attribute :prefecture_id, :big_integer
  attribute :scheduled_delivery_id, :big_integer
  attribute :price, :integer
  attribute :images, :binary
  attribute :user_id, :big_integer
  attribute :tag_name, :string  ## itemのnameと重複するためtagのnameはtag_nameとして扱う
  attribute :id, :integer
  attribute :created_at, :datetime
  attribute :updated_at, :datetime

  # <<バリデーション（ほぼitem.rbの流用）>>

  # 値が入っているか検証
  with_options presence: true do
    validates :images
    validates :name
    validates :info
    validates :price

  end

  # 金額が半角であるか検証
  validates :price, numericality: { message: 'Half-width number' }

  # 金額の範囲
  validates_inclusion_of :price, in: 300..9_999_999, message: 'Out of setting range'

  def save
    item = Item.new(
      name: name,
      info: info,
      price: price,
      category_id: category_id,
      sales_status_id: sales_status_id,
      shipping_fee_status_id: shipping_fee_status_id,
      prefecture_id: prefecture_id,
      scheduled_delivery_id: scheduled_delivery_id,
      user_id: user_id,
      images: images)

    if self.tag_name.present? # タグ欄の記入があれば
      ## 同じタグが作成されることを防ぐため、first_or_initializeで既に存在しているかチェックする
      tag = Tag.where(name: self.tag_name).first_or_initialize
      item.tags << tag
    end
    
    item.save
  end

  def update(params, item)
    ## paramsからtag_nameを除外し、除外したものを変数tag_nameに入れる
    ## ※ハッシュ.delete(:キー)で、ハッシュの中から渡したキーとそのバリューが削除され、バリューが返される
    ## 結果的にparamsから:tag_nameのキーとバリューが削除され、tag_nameに削除されたバリューが入る
    tag_name = params.delete(:tag_name)
    ## tag_nameが空ではない場合はタグを作る。first_or_initializeで重複がないかを確認しておく。
    ## ※先にtagを定義しておかないとrescue内でtagが使えない
    tag = Tag.where(name: tag_name).first_or_initialize if tag_name.present?
    ActiveRecord::Base.transaction do
      tag.save if tag_name.present?
      ## updateに!をつけると失敗したらrescueへ
      item.update!(params)
      ## itemから一旦タグを外す。
      item.item_tag_relations.destroy_all
      ## tag_nameがある場合はタグを付け直す。tag_nameがない場合はタグが0個になる
      ## ※タグがバリデーションに引っかかるとここでrescueへ行く
      item.tags << tag if tag_name.present?
      ## 成功であることを呼び出し元であるコントローラに伝えて終了
      return true
    end
    rescue => e
      ## なんらかのバリデーションに引っかかったとき、フォームオブジェクトへエラーメッセージを足していく

      ## itemのnameとtagのnameでエラーメッセージのキーが重複するため、tagはtag_nameとしておく
      tag.errors.messages[:tag_name] = tag.errors.messages.delete(:name) if tag&.errors&.messages&.present?
      ## itemのエラーメッセージをitem_formオブジェクトのエラーメッセージに追加していく
      item&.errors&.messages&.each do |key, message|
        self.errors.add(key, message.first)
      end
      ## tagのエラーメッセージをitem_formオブジェクトのエラーメッセージに追加していく
      tag&.errors&.messages&.each do |key, message|
        self.errors.add(key, message.first)
      end
      ## 失敗したことを呼び出し元であるコントローラに伝えて終了
      return false
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :purchase_confirm, :purchase]
  before_action :select_item, only: [:show, :edit, :update, :destroy, :purchase_confirm, :purchase]
  before_action :set_item_form, only: [:edit, :update]
  before_action :sold_item, only: [:purchase_confirm, :purchase]
  before_action :current_user_has_not_card, only: [:purchase_confirm, :purchase]

  def index
    @items = Item.all.order(created_at: :desc)
  end

  def new
    @item_form = ItemForm.new
  end

  def create
    @item_form = ItemForm.new(item_form_params)
    # バリデーションで問題があれば、保存はされず「商品出品画面」を再描画
    if @item_form.valid?
      @item_form.save
      return redirect_to root_path
    end
    # アクションのnewをコールすると、エラーメッセージが入った@itemが上書きされてしまうので注意
    render 'new'
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    @favorites_count = Favorite.where(item_id: @item.id).count
  end

  def edit
    @item_form.tag_name = @item.tags.first&.name
    redirect_to root_path if current_user.id != @item.user_id
  end

  def update
    render 'edit' unless current_user.id == @item.user.id
    @item_form = ItemForm.new(item_form_params)
    if @item_form.update(item_form_params, @item)
      return redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def purchase_confirm
    @address = Address.new
    @m = current_user.membership
  end

  def purchase
    ## 購入履歴オブジェクトを定義
    order = Order.new(item_id: @item.id, user_id: current_user.id)

    ## 購入履歴オブジェクトに紐づく配送先オブジェクトを定義
    @address = order.build_address(address_params)
    if @address.valid?
      ## 配送先を保存できるとき
      Payjp.api_key = ENV['PAYJP_SK']      
      Payjp::Charge.create(
        amount: @item.price,
        customer: current_user.card.customer_token,  ## 顧客のトークンを渡す
        currency: 'jpy'
      )

      @address.save
      redirect_to root_path
    else
      ## 配送先を保存できないとき
      redirect_to purchase_confirm_item_path(@item)
    end
  end

  def search
    ## params[:q]がnilではなくて尚且つparams[:q][:name]がnilではないとき
    if params[:q]&.dig(:name)  ## if params[:q] && params[:q][:name]と同じようなもの
      ## squishメソッドで無駄なスペースを圧縮する
      ## 例えば "hoge         fuga    foo  bar"は"hoge fuga foo bar"になる
      squished_keywords = params[:q][:name].squish
      ## 半角スペースを区切り文字として配列にしてparamsに入れる
      ## 例えば文字列"hoge fuga foo bar"は配列[hoge, fuga, foo, bar]になる
      params[:q][:name_cont_any] = squished_keywords.split(" ")
    end

    @q = Item.ransack(params[:q])
    @items = @q.result
  end

  private
  def item_form_params
    params.require(:item_form).permit(
      :name,
      :price,
      :info,
      :scheduled_delivery_id,
      :shipping_fee_status_id,
      :prefecture_id,
      :sales_status_id,
      :category_id,
      :tag_name, 
      {images: []}     
    ).merge(user_id: current_user.id)
  end

  def address_params
    params.permit(
      :postal_code,
      :prefecture_id,
      :city,
      :addresses,
      :building,
      :phone_number
    )
  end

  def select_item
    @item = Item.find(params[:id])
  end

  def set_item_form
    item_attributes = @item.attributes
    @item_form = ItemForm.new(item_attributes)
  end

  ## 購入履歴がある（売り切れ）なら商品の詳細ページにリダイレクト
  def sold_item
    redirect_to item_path(@item), alert: "売り切れの商品です" if @item.order.present?
  end

  ## ユーザーがカードを登録していないならカードの登録ページにリダイレクト
  def current_user_has_not_card
    redirect_to new_card_path, alert: "クレジットカードが登録されていません" unless current_user.card.present?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<% breadcrumb :edit_item, @item %>
<%= render partial: 'form', locals: {url: item_path, method: :patch} %>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
    <%= image_tag "top.png", class:"title-contents" %>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      Neighborhoodが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <div class='list-left'>
          <%= image_tag "furima-intro01.png", class:"list-pict" %>
          <span class='reason-list-number'>1</span>
        </div>
        <div class='list-right'>
          <h3 class='reason-list-text'>
            <span class='reason-list-blue-text'>3分</span>
            ですぐに出品
          </h3>
          <p class='reason-list-description'>
            スマホで入力するだけで簡単に出品できる！
          </p>
        </div>
      </li>
      <li class='list'>
        <div class='list-left'>
          <%= image_tag "furima-intro02.png", class:"list-pict" %>
          <span class='reason-list-number'>2</span>
        </div>
        <div class='list-right'>
          <h3 class='reason-list-text'>
            <span class='reason-list-blue-text'>シンプル</span>
            で使いやすい
          </h3>
          <p class='reason-list-description'>
            めんどくさい入力は必要なく、検索も購入もスムーズ！
          </p>
        </div>
      </li>
      <li class='list'>
        <div class='list-left'>
          <%= image_tag "furima-intro03.png", class:"list-pict" %>
          <span class='reason-list-number'>3</span>
        </div>
        <div class='list-right'>
          <h3 class='reason-list-text'>
            手数料
            <span class='reason-list-blue-text'>業界最安</span>
          </h3>
          <p class='reason-list-description'>
            最大3%でお得に出品&購入！
          </p>
        </div>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      Neighborhoodは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      ネイバー会員になってもっとおトクにStayHome！
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          出品者との交渉
        </h3>
        <p class='feature-list-description'>
          DM機能で、出品者と直接メッセージのやり取りが可能に！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          配送先情報の登録
        </h3>
        <p class='feature-list-description'>
          よく使う配送先を登録することで、お買い物がよりスムーズに！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          ネイバーランク制度
        </h3>
        <p class='feature-list-description'>
          購入額・売上額に応じて4段階の会員ランクを付与！お得な特典がいっぱい！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>
  <div class="furimar-contents">
    <%= link_to 'ネイバー会員登録', new_membership_path, class:"item-red-btn"%>
  </div>
  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%= link_to '新規投稿商品', "#", class: "subtitle" %>
    <ul class='item-lists'>
    <% if @items.length != 0 %>
    <% @items.each do |item| %>
      <%# 商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.images[0], class: "item-img" %>


          <%# 商品が売れていればsold outを表示しましょう %>
          <% if item.order %>
            <div class='sold-out'>
              <span>Sold Out!!</span>
            </div>
          <% end %>
          <%# //商品が売れていればsold outを表示しましょう %>

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= item.favorites.count %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
      <% end %>
      <%# 商品がない場合のダミー %>
      <% else %>
      <%# 商品がある場合は表示されないようにしましょう %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "sample.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <%# //商品がある場合は表示されないようにしましょう %>
      <%# /商品がない場合のダミー %>
      <% end %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<div class='purchase-btn'>
  <span class='purchase-btn-text'>出品する</span>
  <a href="/items/new">
    <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </a>
</div>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<% breadcrumb :new_item %>
<%= render partial: 'form', locals: {url: items_path, method: :post} %>

app/views/items/purchase_confirm.html.erb
<% breadcrumb :purchase_with_card, @item %>
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @item.images[0], class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @item.name %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= @item.price %></p>
          <p class='item-price-sub-text'>（税込）送料込み</p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= @item.price %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with url: purchase_item_path, id: 'item-purchase-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%= render 'shared/error_messages', model: @address %>
    <%# /カード情報の入力 %>
    <%# 配送先の入力 %>
    <%= render "orders/address", f: f , m: @m %>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/items/search.html.erb
<%= render "shared/header" %>
<div class='main' id="detailed-search-wrapper">

  <%= search_form_for @q, url: search_items_path, html: {id: "detailed-search-form"} do |f| %>

    <div class="search-field">
      <%= f.label :name, '商品名' %>
      <br>
      <%= f.text_field :name, placeholder: '商品名', value: params[:q]&.dig(:name) %>
    </div>
    <div class="search-field">
      <%= f.label :user_nickname_cont, '出品者名' %>
      <br>
      <%= f.text_field :user_nickname_cont, placeholder: '出品者名' %>
    </div>
    <div class="search-field">
      <%= f.label :category_id_in, 'カテゴリ' %>
      <br>
      <%= f.collection_check_boxes :category_id_in, Category.all, :id, :name, {include_blank: "---"} %>
    </div>
    <div class="search-field">
      <%= f.label :sales_status_id_eq, '状態' %>
      <br>
      <%= f.collection_select :sales_status_id_eq, SalesStatus.all, :id, :example, {include_blank: "---"} %>
    </div>

    <div class="search-field">
      <%= f.label :shipping_fee_status_id_eq, '送料負担' %>
      <br>
      <%= f.collection_select :shipping_fee_status_id_eq, ShippingFeeStatus.all, :id, :fee, {include_blank: "---"} %>
    </div>
    <div class="search-field">
      <%= f.label :scheduled_delivery_id_eq, '発送日目安' %>
      <br>
      <%= f.collection_select :scheduled_delivery_id_eq, ScheduledDelivery.all, :id, :date, {include_blank: "---"} %>
    </div>

    <div class="search-field">
      <%= f.label :prefecture_id_eq, '発送元地域' %>
      <br>
      <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, {include_blank: "---"} %>
    </div>
    <div class="search-field">
      <%= f.label :price_gteq, '価格'%>
      <br>
      <%= f.number_field :price_gteq %>
      <br>
      ～
      <br>
      <%= f.number_field :price_lteq %>
    </div>

    <%= f.submit '検索' %>
  <% end %>

  <%# 商品一覧 %>
  <div class='item-contents' id="detailed-search-result-wrapper">
    <%= link_to '新規投稿商品', new_item_path, class: "subtitle" %>
    <ul class='item-lists' id="detailed-search-result">
      <% if @items[0] != nil%>
        <% @items.each do |item|%>
          <li class='list'>
            <%= link_to item_path(item.id) do %>
              <div class='item-img-content'>
                <%= image_tag item.images[0], class: "item-img" %>
                <%# sold outの表示 %>
                <% if item.order != nil %>
                  <div class='sold-out'>
                    <span>Sold Out!!</span>
                  </div>
                <% end %>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= item.name %>
                </h3>
                <div class='item-price'>
                  <span><%= item.price %>円<br>(税込み)</span>
                  <div class='star-btn'>
                    <%= image_tag "star.png", class:"star-icon" %>
                    <span class='star-count'>0</span>
                  </div>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      <% end %>

    </ul>
  </div>
  <%# //商品一覧 %>
</div>
<a href="/items/new">
  <div class='purchase-btn'>
    <span class='purchase-btn-text'>出品する</span>
    <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </div>
</a>

<%= render "shared/footer" %>

app/views/items/show.html.erb
<% breadcrumb :show_item, @item %>
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @item.images[0] ,class:"item-box-img" %>
      <%# 商品が売れている場合は、sold outを表示しましょう %>
      <% if @item.order %>
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div>
      <% end %>
      <%# //商品が売れている場合は、sold outを表示しましょう %>
    </div>
    <div id='item-mini-images' style="display:flex;">
      <% @item.images[1..-1].each do |image|%>
        <%= image_tag image.variant(resize:'300x300')%>
      <%end%>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @item.price %>
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>
    </div>

    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
    <% if user_signed_in? && @item.order == nil%>
      <% if current_user.id == @item.user_id %>
        <%= link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
        <p class='or-text'>or</p>
        <%= link_to '削除', item_path(@item.id), method: :delete, class:'item-destroy' %>
      <% else %>
        <%= link_to '購入画面に進む（新しくカードを登録する）', item_orders_path(item_id: @item.id) ,class:"item-red-btn"%>
        <%= link_to '購入画面に進む（カード登録済み）', purchase_confirm_item_path(item_id: @item.id) ,class:"item-red-btn"%>
      <% end %>
    <% end %>

    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <span><%= @item.info %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= link_to "#{@item.user.nickname}", user_path(@item.user.id) %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">タグ</th>
          <td class="detail-value"><%= @item.tags&.first&.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.sales_status.example %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.shipping_fee_status.fee %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.scheduled_delivery.date %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div id="fav">
        <%= render "favorites/favorite", item: @item, favorites_count: @favorites_count %>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
    <div class='comments-container'>
      <h3>コメント一覧</h3>
      <div id="comments">
        <% @comments.each do |comment| %> 
          <div id="comment_<%= comment.id %>">  
            <p class="comment"><%= comment.user.nickname %>：  <%= comment.text %>　　<%= link_to "削除", item_comment_path(item_id: @item.id, comment_id: comment.id), method: :delete, class: "delete-comment-btn" %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>
    
  <div class="comment-box">
    <%= form_with model: [@item, @comment] do |f| %>
      <%= f.text_area :text, class: "comment-text" %>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <%= f.button type: 'submit', class: "comment-btn" do %>
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      <% end %>
    <% end %>
  </div>
  
  <div class="links">
    <div class="link-left">
      <% if @item.next.present? %>
        <%= link_to '◀︎', item_path(@item.next), class: "change-item-btn-next" %>
      <% end %>
    </div>
    <div class="link-right">
      <% if @item.previous.present? %>
        <%= link_to '▶︎', item_path(@item.previous), class: "change-item-btn-previous" %>
      <% end %>
    </div>
  </div>
  <a href="#" class='another-item'><%= "商品のカテゴリー名" %>をもっと見る</a>
</div>

<%= render "shared/footer" %>